### PR TITLE
Add support for basic markdown tables

### PR DESCRIPTION
**Pull request by mblaettler**
Add optional (default disabled) option to allow basic markdown tables.
The method added will convert the markdown table to a reStructuredText table on the fly
and passes it to docutils to create a node.

Please provide feedback for my suggested solution.

### CODE REVIEW

**Comment by mblaettler** [comment]
These changes do not work with CommonMark 0.7.3 (PR #63)

**Comment by likaiguo** [comment]
wish this feature be merged as soon

**Comment by mblaettler** [comment]
@likaiguo This merge request is deprecated. It stopped working with the CommonMark 0.7.3 release.

I'm currently not working on a solution for the current version of recommonmark.  
Sorry

**Comment by codejamninja** [comment]
@mblaettler, take a look at the following pull request.

It has been suggested to rebuild the recommonmark parser to use the [Markdown](https://python-markdown.github.io) python module. This parser supports extensions and has a very solid extension for parsing markdown tables.

I have created a pull request to add the Markdown parser.
#138

It not only enables full markdown support using the [Markdown](https://python-markdown.github.io/) python module but also opens the door for more features supported by the Markdown modules various [extensions](https://python-markdown.github.io/extensions).

I have ensured the pull request is fully backward compatible with the CommonMark parser.

In order to use the Markdown parser this pull request implements, you have to explicitly set the `parser` property in the `recommonmark_config` to `Markdown`.

```py
    app.add_config_value('recommonmark_config', {
        'parser': 'Markdown'
    }, True)
```

You can see my code at the link below.
https://github.com/codejamninja/recommonmark/tree/codejamninja/python-markdown

**Comment by simonsan** [comment]
This is working https://github.com/ryanfox/sphinx-markdown-tables

**Pull request closed without merging**
