### PR TITLE
Auto Directive generation

### PR DESCRIPTION
**Pull request by tqchen**
Squashed push into three commits. Currently the transformer sits in a standalone module, maybe should consider to apply it after parsing by default(with some option to enable some of them).

I am not very familiar with sphinx and docutil configuration, so maybe you guys can have some further changes on it.

### CODE REVIEW

**Comment by tqchen** [comment]
Updates, one more commit to refactor out the codeblock highlighting to the transformer and add support for latex math block. This simplifies the code parsing code in parser.

I did not yet by default add the transform to parser, but I think it might be a good idea to do so

**Comment by tqchen** [comment]
Another commit that added the config setting from document.env.config. Autostructify can be added either via sphinx.add_transform, or can be added by default to parser. 
In long term, hopefully it can be enabled by default enabled for all markdown parsing. I think this is end of updates of this PR.

**Comment by lu-zero** [comment]
Beside the first commit that looks a stray the rest looks fine for me, if nobody has opinions I'd merge it in 24 hours.

**Comment by ericholscher** [comment]
Would love to see a basic test suite for this -- I realize we don't have much in the ways of tests currently, but it's hard for me to verify this visually, and having some tests would make me much more confident.

I can try and get a basic suite started this week, but won't block merging this on that.

I feel the same with documentation -- this seems like a good feature that we would want to document the usage of, or at least explain the mechanism that it works in our docs so people can use it well.

**Comment by tqchen** [comment]
For quick reference, I pushed this contributions because I needed them for my project. Here are two examples I build from what was pushed so far

http://xgboost.readthedocs.org/en/latest/ source https://github.com/dmlc/xgboost/tree/master/doc

http://rabit.readthedocs.org/en/latest/ source https://github.com/dmlc/rabit/tree/master/doc

**Comment by tqchen** [comment]
alrite, there is another commit that pushes in the docs. I think this is the final commit I would make for the PR.

**Comment by tqchen** [comment]
I liked this project a lot, basically this allows us to create documents that are readable and rendered reasonably in github, and being able to generate docs with sphinx. Maybe consider mention it in motivation after it get merged

**Comment by ericholscher** [comment]
Great, thanks! :)

**Pull request merged**
