### PR TITLE
add inline math

### PR DESCRIPTION
**Pull request by tqchen**
This PR adds the inline math into recommonmark.

### CODE REVIEW

**Comment by tqchen** [comment]
@ericholscher any updates on this?

**Comment by agjohnson** [comment]
This seems to be going down a slippery slope of adding magic to the parsing, something I thought we were avoiding by adhering to the commonmark spec. I'm very much -1 on competing markdown specs in general, and would prefer we work towards using a markdown extension syntax.

**Comment by tqchen** [comment]
This is NOT added to parser, instead achieved as using the AutoStructify
Transformers (see doc), which could be disabled.  The parser remains as
plain good commonmark parser, which means all the syntax are commonmark
compatible.

The syntax is adhere to commonmark spec in a sense that this is basically
literal blocks, and they will be rendered as literal blocks with $ sign in
worst case when the option is not enabled.
The general idea of AutoStructify is to adhere to commonmark but doing
something smart to find structure component  in the code and structify it,
so you get some capability of rst out of markdown.

Tianqi

**Comment by tqchen** [comment]
I think the principle is not to disturb what user could have already write in commonmark, and make the extension natural as transformer but not being part of parser.

- For example, it is abnormal for user to write $ in literal blocks and actually intended to display them as it is, instead of math formula.
- Existing things like auto toc tree and auto doc-ref in the AutoStructify module allows generating things that user would have been written otherwise in markdown, except that they are not structured and not understood by sphinx.

For me as a users, [AutoStructify](http://recommonmark.readthedocs.org/en/latest/auto_structify.html) makes  recommonmark usable today within current commonmark spec, and allow user to achieve what they want from rst, while the commonmark spec can keep involve to take over these parts

**Comment by agjohnson** [comment]
Regardless of where this is happening -- if it is part of the commonmark parsing or if it is a post-processing step and part of AutoStructify -- it still special cases syntax that is particular to this implementation, which starts to turn this back into a Markdown flavor. Obviously, without an extension spec, our only options are special case syntax or don't support it at all. I lean towards not supporting features like this at all, until we do have a candidate for an extension spec, but I do want this implementation to be useful for others.

Parts of AutoStructify make a good deal of sense, like the need to retarget references. I'm hesitant to continue throwing special cases in code blocks in the post-processing steps here, though. At least by default. Maybe these syntax special cases inside code blocks should be marked as experimental and not enabled by default? We should expect users to use if enabled by default, and removing these special cases in the future is nearly certain.

Anyways, just my thoughts. I'm not entirely certain what the best path is. We are adhering to the commonmark spec here, but, in a strict sense, we *are* also deviating. I think that's a design decision that needs to be taken into consideration.

**Comment by tqchen** [comment]
Most of the things that I contributed are mainly because we need them to use recommonmark today with sphinx. The inline math formula comes  handy here in [our docs](http://xgboost.readthedocs.org/en/latest/model.html)

I agree careful things need to be done to take care of part of syntax, and try not introduce too much special syntax. I would argue the latex style syntax is nice and natural, and won't disturb things as user usually won't write these syntax.

From what we experience so far, the features current autostructify is all we need to switch from rst to recommonmark and we like it greatly.

**Comment by tqchen** [comment]
@ericholscher @agjohnson  I think I would like to revisit this. As it has been a month and this PR has not been acted upon. This is an useful feature that enables recommonmark to fully usable.

We are using it very seriously in our projects, both of which are quite popular softwares in github.

- http://mxnet.readthedocs.org/en/latest/
- http://xgboost.readthedocs.org/en/latest/

I also find surprisingly, recommonmark enables what was not possible before in sphinx. Documenting R tutorials, see http://mxnet.readthedocs.org/en/latest/R-package/mnistCompetition.html As R's documentation pipeline(Rmarkdown) can be generates the markdown output fairly easily but not rst files.

All of these could not have been possible without the early "hacks" around markdown syntax that is compatible with existing one and gives the things needed.

I really hope these experience can be incorporated to make this project great for users today, and smoothly transfer to future better world

**Comment by ericholscher** [comment]
Went ahead and merged this, but I generally agree with @agjohnson -- I would love to not have custom actions inside of our version of Commonmark, but actually build these as extensions. This is currently the best way to build these extensions with the current spec, but once we support generic inline & block level markup, it should be moved into that: http://talk.commonmark.org/t/generic-directives-plugins-syntax/444

**Comment by tqchen** [comment]
Thanks! @ericholscher in general I agree. As users, I think we have what we need in the current modules.

**Pull request merged**
