### PR TITLE
Fix regression with highliting

### PR DESCRIPTION
**Pull request by pfultz2**
This fixes a regression where pygments would no longer highlight indented code.

### CODE REVIEW

**Comment by ericholscher** [comment]
Great! A test that verifies this would be great to make sure we don't regress again. I know the project isn't super well tested, but at least verifying the pygments HTML output is there for a basic string or some type of integration test would be a good start.

**Comment by pfultz2** [comment]
I'll try to look into it, but the document will need to be generated with sphinx, I believe, to check for pygments.

**Comment by ericholscher** [comment]
Yea -- https://github.com/rtfd/sphinx-autoapi/blob/master/tests/test_integration.py might be a useful place to start.

**Comment by pfultz2** [comment]
Ok, I've add tests for this, but it requires using a newer version of sphinx for the highlighting to work, so I updated the requirements as well.

**Comment by pfultz2** [comment]
Any chance to look at this?

**Comment by ericholscher** [comment]
Looks great! Thanks.

**Pull request merged**
